### ISSUE TITLE
Null values flagged as errors

### ISSUE THREAD

**Issue by ZebraFlesh** [Lona/vscode-github-actions#19]
Null values are flagged as errors. For example, the following is valid YAML which GitHub accepts and runs without issue, however, this extension flags the null value on the last line as an error:

```yaml
name: TOC Generator

on: push

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v2
        with:
          TOC_TITLE: ~
```
